name: 'DB Migration Setup'
description: 'Prepare a database connection to run migrations'
inputs:
  env:
    description: 'dev | qa | prod'
    required: true
  key:
    description: 'GCP service key base64 encoded'
    required: true
  service:
    description: 'name of the service without the -service suffix'
    required: true
  region:
    description: 'GCP region'
    required: false
    default: 'europe-west4'
  go_version:
    description: 'Go version'
    required: false
    default: '1.21'
runs:
  using: "composite"
  steps:
    - name: Prevent file overwrite errors
      shell: bash
      run: echo "GOTOOLCHAIN=local" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: nf-environment-${{ inputs.env }}
        
    - name: Prepare database connection
      shell: bash
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: ${{ inputs.service }}-migration-${{ inputs.env }}
        DB_GCP_SOCKET: false
        ENV: ${{ inputs.env }}
      run: |
        export RAW_SCHEMA=${{ inputs.service }}_${{ inputs.env }}
        export DB_SCHEMA="${RAW_SCHEMA//-/_}"
        echo "applying migrations on schema ${DB_SCHEMA}"
        echo "extract gcp authentication"
        echo ${{ inputs.key }} | base64 --decode > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        echo "Installing Cloud SQL Proxy..."
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.12.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        export DB_INSTANCE="nf-environment-${{ inputs.env }}:europe-west4:neuroflash-mysql-${{ inputs.env }}"
        echo "Starting Cloud SQL Proxy to ${DB_INSTANCE}..."
        ./cloud-sql-proxy --credentials-file "${HOME}/gcloud-service-key.json" --port 3306 "${DB_INSTANCE}" &
        echo "Waiting for Cloud SQL Proxy to be ready..."
        timeout=60
        while ! nc -z 127.0.0.1 3306; do
          sleep 1
          timeout=$((timeout - 1))
          if [ $timeout -eq 0 ]; then
            echo "Timeout waiting for Cloud SQL Proxy to start"
            exit 1
          fi
        done
        echo "Cloud SQL Proxy is ready after $((60 - timeout)) second(s)!"
        export DB_PASS=$(gcloud secrets versions access latest --secret="db-password-${{ inputs.service }}-migration-${{ inputs.env }}")
        echo "Running DB migrations..."
        go run cmd/db-migrate/main.go
